name: SBURBSim_Dart_Edition
description: A no-longer-javascript SBRUB Story and Original Character generator.
version: 0.0.1
author: jadedResearcher, ParadoxLands

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js: ^0.6.0
  petitparser: ^1.6.1
  xml: ^2.6.0
  source_map_stack_trace: ^1.1.4
  archive: ^1.0.31

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- $dart2js:
    sourceMaps: true
    commandLineOptions: [--fast-startup]
    $exclude: ["web/manifest/bundlebuilder.dart", "web/manifest/sourcemanifest.txt"]

#web:
#  compiler:
#    debug: dartdevc

